[Tree UCSDStudentTree - Allocating]
Initial Symbol Table:
Tree UCSDStudentTree:
occupancy is 0 elements.
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter name of new Tree to allocate:  [Tree UCSDStudentTree has been deallocated]
[Tree alphabet - Allocating]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Inserting a]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing b and a]
[Tree alphabet - Inserting b]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing c and a]
[Tree alphabet - Comparing c and b]
[Tree alphabet - Inserting c]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing d and a]
[Tree alphabet - Comparing d and b]
[Tree alphabet - Comparing d and c]
[Tree alphabet - Inserting d]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing e and a]
[Tree alphabet - Comparing e and b]
[Tree alphabet - Comparing e and c]
[Tree alphabet - Comparing e and d]
[Tree alphabet - Inserting e]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing f and a]
[Tree alphabet - Comparing f and b]
[Tree alphabet - Comparing f and c]
[Tree alphabet - Comparing f and d]
[Tree alphabet - Comparing f and e]
[Tree alphabet - Inserting f]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing g and a]
[Tree alphabet - Comparing g and b]
[Tree alphabet - Comparing g and c]
[Tree alphabet - Comparing g and d]
[Tree alphabet - Comparing g and e]
[Tree alphabet - Comparing g and f]
[Tree alphabet - Inserting g]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing h and a]
[Tree alphabet - Comparing h and b]
[Tree alphabet - Comparing h and c]
[Tree alphabet - Comparing h and d]
[Tree alphabet - Comparing h and e]
[Tree alphabet - Comparing h and f]
[Tree alphabet - Comparing h and g]
[Tree alphabet - Inserting h]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing i and a]
[Tree alphabet - Comparing i and b]
[Tree alphabet - Comparing i and c]
[Tree alphabet - Comparing i and d]
[Tree alphabet - Comparing i and e]
[Tree alphabet - Comparing i and f]
[Tree alphabet - Comparing i and g]
[Tree alphabet - Comparing i and h]
[Tree alphabet - Inserting i]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing j and a]
[Tree alphabet - Comparing j and b]
[Tree alphabet - Comparing j and c]
[Tree alphabet - Comparing j and d]
[Tree alphabet - Comparing j and e]
[Tree alphabet - Comparing j and f]
[Tree alphabet - Comparing j and g]
[Tree alphabet - Comparing j and h]
[Tree alphabet - Comparing j and i]
[Tree alphabet - Inserting j]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing k and a]
[Tree alphabet - Comparing k and b]
[Tree alphabet - Comparing k and c]
[Tree alphabet - Comparing k and d]
[Tree alphabet - Comparing k and e]
[Tree alphabet - Comparing k and f]
[Tree alphabet - Comparing k and g]
[Tree alphabet - Comparing k and h]
[Tree alphabet - Comparing k and i]
[Tree alphabet - Comparing k and j]
[Tree alphabet - Inserting k]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing l and a]
[Tree alphabet - Comparing l and b]
[Tree alphabet - Comparing l and c]
[Tree alphabet - Comparing l and d]
[Tree alphabet - Comparing l and e]
[Tree alphabet - Comparing l and f]
[Tree alphabet - Comparing l and g]
[Tree alphabet - Comparing l and h]
[Tree alphabet - Comparing l and i]
[Tree alphabet - Comparing l and j]
[Tree alphabet - Comparing l and k]
[Tree alphabet - Inserting l]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing m and a]
[Tree alphabet - Comparing m and b]
[Tree alphabet - Comparing m and c]
[Tree alphabet - Comparing m and d]
[Tree alphabet - Comparing m and e]
[Tree alphabet - Comparing m and f]
[Tree alphabet - Comparing m and g]
[Tree alphabet - Comparing m and h]
[Tree alphabet - Comparing m and i]
[Tree alphabet - Comparing m and j]
[Tree alphabet - Comparing m and k]
[Tree alphabet - Comparing m and l]
[Tree alphabet - Inserting m]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing n and a]
[Tree alphabet - Comparing n and b]
[Tree alphabet - Comparing n and c]
[Tree alphabet - Comparing n and d]
[Tree alphabet - Comparing n and e]
[Tree alphabet - Comparing n and f]
[Tree alphabet - Comparing n and g]
[Tree alphabet - Comparing n and h]
[Tree alphabet - Comparing n and i]
[Tree alphabet - Comparing n and j]
[Tree alphabet - Comparing n and k]
[Tree alphabet - Comparing n and l]
[Tree alphabet - Comparing n and m]
[Tree alphabet - Inserting n]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing o and a]
[Tree alphabet - Comparing o and b]
[Tree alphabet - Comparing o and c]
[Tree alphabet - Comparing o and d]
[Tree alphabet - Comparing o and e]
[Tree alphabet - Comparing o and f]
[Tree alphabet - Comparing o and g]
[Tree alphabet - Comparing o and h]
[Tree alphabet - Comparing o and i]
[Tree alphabet - Comparing o and j]
[Tree alphabet - Comparing o and k]
[Tree alphabet - Comparing o and l]
[Tree alphabet - Comparing o and m]
[Tree alphabet - Comparing o and n]
[Tree alphabet - Inserting o]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing p and a]
[Tree alphabet - Comparing p and b]
[Tree alphabet - Comparing p and c]
[Tree alphabet - Comparing p and d]
[Tree alphabet - Comparing p and e]
[Tree alphabet - Comparing p and f]
[Tree alphabet - Comparing p and g]
[Tree alphabet - Comparing p and h]
[Tree alphabet - Comparing p and i]
[Tree alphabet - Comparing p and j]
[Tree alphabet - Comparing p and k]
[Tree alphabet - Comparing p and l]
[Tree alphabet - Comparing p and m]
[Tree alphabet - Comparing p and n]
[Tree alphabet - Comparing p and o]
[Tree alphabet - Inserting p]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing q and a]
[Tree alphabet - Comparing q and b]
[Tree alphabet - Comparing q and c]
[Tree alphabet - Comparing q and d]
[Tree alphabet - Comparing q and e]
[Tree alphabet - Comparing q and f]
[Tree alphabet - Comparing q and g]
[Tree alphabet - Comparing q and h]
[Tree alphabet - Comparing q and i]
[Tree alphabet - Comparing q and j]
[Tree alphabet - Comparing q and k]
[Tree alphabet - Comparing q and l]
[Tree alphabet - Comparing q and m]
[Tree alphabet - Comparing q and n]
[Tree alphabet - Comparing q and o]
[Tree alphabet - Comparing q and p]
[Tree alphabet - Inserting q]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing r and a]
[Tree alphabet - Comparing r and b]
[Tree alphabet - Comparing r and c]
[Tree alphabet - Comparing r and d]
[Tree alphabet - Comparing r and e]
[Tree alphabet - Comparing r and f]
[Tree alphabet - Comparing r and g]
[Tree alphabet - Comparing r and h]
[Tree alphabet - Comparing r and i]
[Tree alphabet - Comparing r and j]
[Tree alphabet - Comparing r and k]
[Tree alphabet - Comparing r and l]
[Tree alphabet - Comparing r and m]
[Tree alphabet - Comparing r and n]
[Tree alphabet - Comparing r and o]
[Tree alphabet - Comparing r and p]
[Tree alphabet - Comparing r and q]
[Tree alphabet - Inserting r]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing s and a]
[Tree alphabet - Comparing s and b]
[Tree alphabet - Comparing s and c]
[Tree alphabet - Comparing s and d]
[Tree alphabet - Comparing s and e]
[Tree alphabet - Comparing s and f]
[Tree alphabet - Comparing s and g]
[Tree alphabet - Comparing s and h]
[Tree alphabet - Comparing s and i]
[Tree alphabet - Comparing s and j]
[Tree alphabet - Comparing s and k]
[Tree alphabet - Comparing s and l]
[Tree alphabet - Comparing s and m]
[Tree alphabet - Comparing s and n]
[Tree alphabet - Comparing s and o]
[Tree alphabet - Comparing s and p]
[Tree alphabet - Comparing s and q]
[Tree alphabet - Comparing s and r]
[Tree alphabet - Inserting s]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing t and a]
[Tree alphabet - Comparing t and b]
[Tree alphabet - Comparing t and c]
[Tree alphabet - Comparing t and d]
[Tree alphabet - Comparing t and e]
[Tree alphabet - Comparing t and f]
[Tree alphabet - Comparing t and g]
[Tree alphabet - Comparing t and h]
[Tree alphabet - Comparing t and i]
[Tree alphabet - Comparing t and j]
[Tree alphabet - Comparing t and k]
[Tree alphabet - Comparing t and l]
[Tree alphabet - Comparing t and m]
[Tree alphabet - Comparing t and n]
[Tree alphabet - Comparing t and o]
[Tree alphabet - Comparing t and p]
[Tree alphabet - Comparing t and q]
[Tree alphabet - Comparing t and r]
[Tree alphabet - Comparing t and s]
[Tree alphabet - Inserting t]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing u and a]
[Tree alphabet - Comparing u and b]
[Tree alphabet - Comparing u and c]
[Tree alphabet - Comparing u and d]
[Tree alphabet - Comparing u and e]
[Tree alphabet - Comparing u and f]
[Tree alphabet - Comparing u and g]
[Tree alphabet - Comparing u and h]
[Tree alphabet - Comparing u and i]
[Tree alphabet - Comparing u and j]
[Tree alphabet - Comparing u and k]
[Tree alphabet - Comparing u and l]
[Tree alphabet - Comparing u and m]
[Tree alphabet - Comparing u and n]
[Tree alphabet - Comparing u and o]
[Tree alphabet - Comparing u and p]
[Tree alphabet - Comparing u and q]
[Tree alphabet - Comparing u and r]
[Tree alphabet - Comparing u and s]
[Tree alphabet - Comparing u and t]
[Tree alphabet - Inserting u]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing v and a]
[Tree alphabet - Comparing v and b]
[Tree alphabet - Comparing v and c]
[Tree alphabet - Comparing v and d]
[Tree alphabet - Comparing v and e]
[Tree alphabet - Comparing v and f]
[Tree alphabet - Comparing v and g]
[Tree alphabet - Comparing v and h]
[Tree alphabet - Comparing v and i]
[Tree alphabet - Comparing v and j]
[Tree alphabet - Comparing v and k]
[Tree alphabet - Comparing v and l]
[Tree alphabet - Comparing v and m]
[Tree alphabet - Comparing v and n]
[Tree alphabet - Comparing v and o]
[Tree alphabet - Comparing v and p]
[Tree alphabet - Comparing v and q]
[Tree alphabet - Comparing v and r]
[Tree alphabet - Comparing v and s]
[Tree alphabet - Comparing v and t]
[Tree alphabet - Comparing v and u]
[Tree alphabet - Inserting v]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing w and a]
[Tree alphabet - Comparing w and b]
[Tree alphabet - Comparing w and c]
[Tree alphabet - Comparing w and d]
[Tree alphabet - Comparing w and e]
[Tree alphabet - Comparing w and f]
[Tree alphabet - Comparing w and g]
[Tree alphabet - Comparing w and h]
[Tree alphabet - Comparing w and i]
[Tree alphabet - Comparing w and j]
[Tree alphabet - Comparing w and k]
[Tree alphabet - Comparing w and l]
[Tree alphabet - Comparing w and m]
[Tree alphabet - Comparing w and n]
[Tree alphabet - Comparing w and o]
[Tree alphabet - Comparing w and p]
[Tree alphabet - Comparing w and q]
[Tree alphabet - Comparing w and r]
[Tree alphabet - Comparing w and s]
[Tree alphabet - Comparing w and t]
[Tree alphabet - Comparing w and u]
[Tree alphabet - Comparing w and v]
[Tree alphabet - Inserting w]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing x and a]
[Tree alphabet - Comparing x and b]
[Tree alphabet - Comparing x and c]
[Tree alphabet - Comparing x and d]
[Tree alphabet - Comparing x and e]
[Tree alphabet - Comparing x and f]
[Tree alphabet - Comparing x and g]
[Tree alphabet - Comparing x and h]
[Tree alphabet - Comparing x and i]
[Tree alphabet - Comparing x and j]
[Tree alphabet - Comparing x and k]
[Tree alphabet - Comparing x and l]
[Tree alphabet - Comparing x and m]
[Tree alphabet - Comparing x and n]
[Tree alphabet - Comparing x and o]
[Tree alphabet - Comparing x and p]
[Tree alphabet - Comparing x and q]
[Tree alphabet - Comparing x and r]
[Tree alphabet - Comparing x and s]
[Tree alphabet - Comparing x and t]
[Tree alphabet - Comparing x and u]
[Tree alphabet - Comparing x and v]
[Tree alphabet - Comparing x and w]
[Tree alphabet - Inserting x]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing y and a]
[Tree alphabet - Comparing y and b]
[Tree alphabet - Comparing y and c]
[Tree alphabet - Comparing y and d]
[Tree alphabet - Comparing y and e]
[Tree alphabet - Comparing y and f]
[Tree alphabet - Comparing y and g]
[Tree alphabet - Comparing y and h]
[Tree alphabet - Comparing y and i]
[Tree alphabet - Comparing y and j]
[Tree alphabet - Comparing y and k]
[Tree alphabet - Comparing y and l]
[Tree alphabet - Comparing y and m]
[Tree alphabet - Comparing y and n]
[Tree alphabet - Comparing y and o]
[Tree alphabet - Comparing y and p]
[Tree alphabet - Comparing y and q]
[Tree alphabet - Comparing y and r]
[Tree alphabet - Comparing y and s]
[Tree alphabet - Comparing y and t]
[Tree alphabet - Comparing y and u]
[Tree alphabet - Comparing y and v]
[Tree alphabet - Comparing y and w]
[Tree alphabet - Comparing y and x]
[Tree alphabet - Inserting y]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  Please enter UCSD student name to insert:  Please enter UCSD student number:  [Tree alphabet - Comparing z and a]
[Tree alphabet - Comparing z and b]
[Tree alphabet - Comparing z and c]
[Tree alphabet - Comparing z and d]
[Tree alphabet - Comparing z and e]
[Tree alphabet - Comparing z and f]
[Tree alphabet - Comparing z and g]
[Tree alphabet - Comparing z and h]
[Tree alphabet - Comparing z and i]
[Tree alphabet - Comparing z and j]
[Tree alphabet - Comparing z and k]
[Tree alphabet - Comparing z and l]
[Tree alphabet - Comparing z and m]
[Tree alphabet - Comparing z and n]
[Tree alphabet - Comparing z and o]
[Tree alphabet - Comparing z and p]
[Tree alphabet - Comparing z and q]
[Tree alphabet - Comparing z and r]
[Tree alphabet - Comparing z and s]
[Tree alphabet - Comparing z and t]
[Tree alphabet - Comparing z and u]
[Tree alphabet - Comparing z and v]
[Tree alphabet - Comparing z and w]
[Tree alphabet - Comparing z and x]
[Tree alphabet - Comparing z and y]
[Tree alphabet - Inserting z]
Please enter a command:  ((a)llocate, is(e)mpty, (i)nsert, (l)ookup, (r)emove, (w)rite):  
Final Symbol Table:
Tree alphabet:
occupancy is 26 elements.
at height:  25  with balance:  -25  name:  a  studentnum:  1
at height:  24  with balance:  -24  name:  b  studentnum:  2
at height:  23  with balance:  -23  name:  c  studentnum:  3
at height:  22  with balance:  -22  name:  d  studentnum:  4
at height:  21  with balance:  -21  name:  e  studentnum:  5
at height:  20  with balance:  -20  name:  f  studentnum:  6
at height:  19  with balance:  -19  name:  g  studentnum:  7
at height:  18  with balance:  -18  name:  h  studentnum:  8
at height:  17  with balance:  -17  name:  i  studentnum:  9
at height:  16  with balance:  -16  name:  j  studentnum:  10
at height:  15  with balance:  -15  name:  k  studentnum:  11
at height:  14  with balance:  -14  name:  l  studentnum:  12
at height:  13  with balance:  -13  name:  m  studentnum:  13
at height:  12  with balance:  -12  name:  n  studentnum:  14
at height:  11  with balance:  -11  name:  o  studentnum:  15
at height:  10  with balance:  -10  name:  p  studentnum:  16
at height:  9  with balance:  -9  name:  q  studentnum:  17
at height:  8  with balance:  -8  name:  r  studentnum:  18
at height:  7  with balance:  -7  name:  s  studentnum:  19
at height:  6  with balance:  -6  name:  t  studentnum:  20
at height:  5  with balance:  -5  name:  u  studentnum:  21
at height:  4  with balance:  -4  name:  v  studentnum:  22
at height:  3  with balance:  -3  name:  w  studentnum:  23
at height:  2  with balance:  -2  name:  x  studentnum:  24
at height:  1  with balance:  -1  name:  y  studentnum:  26
at height:  0  with balance:  0  name:  z  studentnum:  26
[Tree alphabet has been deallocated]
